name: CI-build-image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name:
        run: |
          if [[ -z "$GITHUB_HEAD_REF" ]] # is set only if pipeline run is triggered as pull request
          then
            BRANCH_NAME="${GITHUB_REF#refs/heads/}"
            echo "Setting BRANCH_NAME=$BRANCH_NAME because this pipeline is run as Push"
          else
            BRANCH_NAME=$GITHUB_HEAD_REF
            echo "Setting BRANCH_NAME=$BRANCH_NAME because this pipeline is run as Pull Request"
          fi

          FULL_REPO_SLUG=`echo "${{github.event.pull_request.head.repo.full_name}}" | sed "s/[^[:alnum:]-]//g" | tr '[:upper:]' '[:lower:]'` # lowercase, only alphanumeric and dash
          echo ::set-env name=FULL_REPO_SLUG::$(echo $FULL_REPO_SLUG)

          BRANCH_NAME=`echo $BRANCH_NAME | sed "s/[^[:alnum:]-]//g" | tr '[:upper:]' '[:lower:]'` # lowercase, only alphanumeric and dash
          echo ::set-env name=BRANCH_NAME::$(echo $BRANCH_NAME)
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Cache image
        id: cache-image
        uses: actions/cache@v2
        with:
          path: built-image
          key: $BRANCH_NAME
      - name: Set custom env variables
        run: |
          set -x
          echo "building"
          docker build -t hello_world:$BRANCH_NAME .
      - name: Print file if found in cache
        if: steps.cache-image.outputs.cache-hit == 'true'
        run: |
          mkdir built-image
          ls -lah
          cat built-image/foo.txt
      - name: Create file if not found in cache.
        if: steps.cache-image.outputs.cache-hit != 'true'
        run: |
          mkdir built-image
          ls -lah
          echo "this should be cached" > built-image/foo.txt
      - name: Print file for sure
        run: |
          ls -lah
          cat built-image/foo.txt





