name: CI-on-master-push

on:
  push:
    branches:
      - master

jobs:
  on-push-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print on push
        run: |
          echo "This was trigerred per push event!"
          echo "${{ github.event_name}}"
          echo "echo ${{github.event}}"


