name: CI-on-master-push

on:
  push:
    branches:
      - master

jobs:
  on-push-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print on push
        run: |
          echo "This was trigerred per push event!"
          echo "Event name = ${{ github.event_name}}"
          echo "Github context = ${{ toJson(github) }}"
          echo "Event info ${{ toJson(github.event) }}"


